apiVersion: v1
kind: Service
metadata:
  name: {{ include "staffops-ad.controller.fullname" . }}
  labels:
    {{- include "staffops-ad.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type | default "ClusterIP" }}
  ports:
    - name: metrics
      port: {{ .Values.controller.service.port | default 8080 }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "staffops-ad.controller.selectorLabels" . | nindent 4 }}
